apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: todo-app-backend
    projectName: Default Project
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: Todo App Backend
          port: 5000
          type: REST
          visibility: Public
          context: /
